"""Canonical block identities and serializable per-cell state values."""

from dataclasses import dataclass
from enum import Enum


class BlockType(Enum):
    """Stable block identifiers serialized by name and numeric value."""

    AIR = 0
    GRASS = 1
    DIRT = 2
    STONE = 3
    COBBLESTONE = 4
    GRAVEL = 5
    SAND = 6
    CLAY = 7
    OAK_LOG = 10
    OAK_PLANKS = 11
    OAK_LEAVES = 12
    BIRCH_LOG = 13
    BIRCH_PLANKS = 14
    BIRCH_LEAVES = 15
    SPRUCE_LOG = 16
    SPRUCE_PLANKS = 17
    SPRUCE_LEAVES = 18
    DARK_OAK_LOG = 19
    DARK_OAK_PLANKS = 20
    DARK_OAK_LEAVES = 21
    ACACIA_LOG = 22
    ACACIA_PLANKS = 23
    ACACIA_LEAVES = 24
    JUNGLE_LOG = 25
    JUNGLE_PLANKS = 26
    JUNGLE_LEAVES = 27
    CRIMSON_STEM = 260
    CRIMSON_PLANKS = 261
    WARPED_STEM = 262
    WARPED_PLANKS = 263
    CRIMSON_NYLIUM = 264
    WARPED_NYLIUM = 265
    STRIPPED_OAK_LOG = 270
    STRIPPED_BIRCH_LOG = 271
    STRIPPED_SPRUCE_LOG = 272
    STRIPPED_DARK_OAK_LOG = 273
    STRIPPED_ACACIA_LOG = 274
    STRIPPED_JUNGLE_LOG = 275
    STRIPPED_CRIMSON_STEM = 276
    STRIPPED_WARPED_STEM = 277
    COAL_ORE = 30
    IRON_ORE = 31
    GOLD_ORE = 32
    DIAMOND_ORE = 33
    COAL_BLOCK = 34
    IRON_BLOCK = 35
    GOLD_BLOCK = 36
    DIAMOND_BLOCK = 37
    LAPIS_ORE = 38
    LAPIS_BLOCK = 39
    EMERALD_ORE = 230
    EMERALD_BLOCK = 231
    REDSTONE_ORE = 232
    REDSTONE_BLOCK = 233
    QUARTZ_BLOCK = 234
    QUARTZ_PILLAR = 235
    CHISELED_QUARTZ = 236
    SMOOTH_QUARTZ = 237
    QUARTZ_BRICKS = 238
    BRICKS = 40
    STONE_BRICKS = 41
    MOSSY_STONE_BRICKS = 42
    MOSSY_COBBLESTONE = 43
    SANDSTONE = 44
    RED_SANDSTONE = 45
    GRANITE = 46
    POLISHED_GRANITE = 47
    DIORITE = 48
    POLISHED_DIORITE = 49
    ANDESITE = 280
    POLISHED_ANDESITE = 281
    SMOOTH_STONE = 282
    CHISELED_STONE_BRICKS = 283
    CRACKED_STONE_BRICKS = 284
    GLASS = 50
    BOOKSHELF = 51
    GLOWSTONE = 52
    WHITE_WOOL = 60
    RED_WOOL = 61
    BLUE_WOOL = 62
    GREEN_WOOL = 63
    YELLOW_WOOL = 64
    BLACK_WOOL = 65
    ORANGE_WOOL = 290
    MAGENTA_WOOL = 291
    LIGHT_BLUE_WOOL = 292
    LIME_WOOL = 293
    PINK_WOOL = 294
    GRAY_WOOL = 295
    LIGHT_GRAY_WOOL = 296
    CYAN_WOOL = 297
    PURPLE_WOOL = 298
    BROWN_WOOL = 299
    WHITE_STAINED_GLASS = 300
    ORANGE_STAINED_GLASS = 301
    MAGENTA_STAINED_GLASS = 302
    LIGHT_BLUE_STAINED_GLASS = 303
    YELLOW_STAINED_GLASS = 304
    LIME_STAINED_GLASS = 305
    PINK_STAINED_GLASS = 306
    GRAY_STAINED_GLASS = 307
    LIGHT_GRAY_STAINED_GLASS = 308
    CYAN_STAINED_GLASS = 309
    PURPLE_STAINED_GLASS = 310
    BLUE_STAINED_GLASS = 311
    BROWN_STAINED_GLASS = 312
    GREEN_STAINED_GLASS = 313
    RED_STAINED_GLASS = 314
    BLACK_STAINED_GLASS = 315
    TERRACOTTA = 320
    WHITE_TERRACOTTA = 321
    ORANGE_TERRACOTTA = 322
    MAGENTA_TERRACOTTA = 323
    LIGHT_BLUE_TERRACOTTA = 324
    YELLOW_TERRACOTTA = 325
    LIME_TERRACOTTA = 326
    PINK_TERRACOTTA = 327
    GRAY_TERRACOTTA = 328
    LIGHT_GRAY_TERRACOTTA = 329
    CYAN_TERRACOTTA = 330
    PURPLE_TERRACOTTA = 331
    BLUE_TERRACOTTA = 332
    BROWN_TERRACOTTA = 333
    GREEN_TERRACOTTA = 334
    RED_TERRACOTTA = 335
    BLACK_TERRACOTTA = 336
    WHITE_CONCRETE = 70
    RED_CONCRETE = 71
    BLUE_CONCRETE = 72
    CRAFTING_TABLE = 80
    FURNACE = 81
    TNT = 82
    BEDROCK = 83
    OAK_DOOR = 90
    IRON_DOOR = 91
    WATER = 95
    LAVA = 96
    OAK_STAIRS = 100
    COBBLESTONE_STAIRS = 101
    STONE_BRICK_STAIRS = 102
    OAK_SLAB = 110
    COBBLESTONE_SLAB = 111
    STONE_BRICK_SLAB = 112
    STONE_SLAB = 113
    OBSIDIAN = 120
    END_PORTAL_FRAME = 121
    END_STONE = 122
    END_STONE_BRICKS = 123
    NETHER_PORTAL = 124
    NETHER_BRICKS = 125
    NETHERRACK = 126
    SOUL_SAND = 127
    GLOWSTONE_BLOCK = 128
    CACTUS = 130
    PUMPKIN = 131
    JACK_O_LANTERN = 132
    HAY_BLOCK = 133
    MELON = 134
    CARVED_PUMPKIN = 135
    SPONGE = 240
    WET_SPONGE = 241
    NOTE_BLOCK = 242
    JUKEBOX = 243
    SLIME_BLOCK = 244
    HONEY_BLOCK = 245
    DRAGON_EGG = 246
    PRISMARINE = 250
    PRISMARINE_BRICKS = 251
    DARK_PRISMARINE = 252
    SEA_LANTERN = 253
    PURPUR_BLOCK = 254
    PURPUR_PILLAR = 255
    MAGMA_BLOCK = 256
    BLACKSTONE = 340
    POLISHED_BLACKSTONE = 341
    POLISHED_BLACKSTONE_BRICKS = 342
    CHISELED_POLISHED_BLACKSTONE = 343
    CRACKED_POLISHED_BLACKSTONE_BRICKS = 344
    GILDED_BLACKSTONE = 345
    BASALT = 346
    POLISHED_BASALT = 347
    SMOOTH_BASALT = 348
    NETHER_GOLD_ORE = 349
    ANCIENT_DEBRIS = 350
    NETHERITE_BLOCK = 351
    CRYING_OBSIDIAN = 352
    NETHER_WART_BLOCK = 353
    WARPED_WART_BLOCK = 354
    SHROOMLIGHT = 355
    SOUL_SOIL = 356
    RESPAWN_ANCHOR = 357
    LODESTONE = 358
    TARGET = 359
    DEEPSLATE = 360
    COBBLED_DEEPSLATE = 361
    POLISHED_DEEPSLATE = 362
    DEEPSLATE_BRICKS = 363
    CRACKED_DEEPSLATE_BRICKS = 364
    DEEPSLATE_TILES = 365
    CRACKED_DEEPSLATE_TILES = 366
    CHISELED_DEEPSLATE = 367
    REINFORCED_DEEPSLATE = 368
    SCULK_CATALYST = 369
    SCULK_SHRIEKER = 370
    SNOW = 140
    ICE = 141
    PACKED_ICE = 142
    COPPER_BLOCK = 150
    EXPOSED_COPPER = 151
    WEATHERED_COPPER = 152
    OXIDIZED_COPPER = 153
    CUT_COPPER = 154
    EXPOSED_CUT_COPPER = 155
    WEATHERED_CUT_COPPER = 156
    OXIDIZED_CUT_COPPER = 157
    CHEST = 160
    ENDER_CHEST = 161
    BONE_BLOCK = 162
    SCULK = 163
    TRAPPED_CHEST = 165
    CHRISTMAS_CHEST = 166
    COPPER_CHEST = 167
    COPPER_CHEST_EXPOSED = 168
    COPPER_CHEST_WEATHERED = 169
    COPPER_CHEST_OXIDIZED = 170
    OXIDIZING_COPPER = 200
    ENCHANTING_TABLE = 201
    MOB_SPAWNER = 202
    TRIAL_SPAWNER = 203
    SCULK_SENSOR = 204
    END_PORTAL = 205
    END_GATEWAY = 206
    FIRE = 207
    SOUL_FIRE = 208
    MATRIX = 209  # Legacy save ID retained for the Craftmine Mine Crafter
    TUFF = 400
    POLISHED_TUFF = 401
    TUFF_BRICKS = 402
    CHISELED_TUFF = 403
    CHISELED_TUFF_BRICKS = 404
    DIRT_PATH = 405
    FARMLAND = 406
    WHEAT = 407
    SMOOTH_SANDSTONE = 408
    CUT_SANDSTONE = 409
    POWDER_SNOW = 410
    GLASS_PANE = 411
    LADDER = 412
    CHAIN = 413
    LANTERN = 414
    SOUL_LANTERN = 415
    REDSTONE_LAMP = 416
    VAULT = 417
    DECORATED_POT = 418
    SPRUCE_STAIRS = 420
    ACACIA_STAIRS = 421
    PURPUR_STAIRS = 422
    DEEPSLATE_BRICK_STAIRS = 423
    DEEPSLATE_TILE_STAIRS = 424
    COBBLED_DEEPSLATE_STAIRS = 425
    POLISHED_DEEPSLATE_STAIRS = 426
    BLACKSTONE_STAIRS = 427
    POLISHED_BLACKSTONE_BRICK_STAIRS = 428
    SPRUCE_SLAB = 430
    ACACIA_SLAB = 431
    PURPUR_SLAB = 432
    DEEPSLATE_BRICK_SLAB = 433
    DEEPSLATE_TILE_SLAB = 434
    COBBLED_DEEPSLATE_SLAB = 435
    POLISHED_DEEPSLATE_SLAB = 436
    BLACKSTONE_SLAB = 437
    POLISHED_BLACKSTONE_BRICK_SLAB = 438
    SPRUCE_DOOR = 440
    ACACIA_DOOR = 441
    JUNGLE_DOOR = 442
    CHORUS_PLANT = 450
    CHORUS_FLOWER = 451
    CRIMSON_FUNGUS = 452
    WARPED_FUNGUS = 453
    NETHER_SPROUTS = 454
    TWISTING_VINES = 455
    WEEPING_VINES = 456
    SMOOTH_SANDSTONE_SLAB = 460
    SANDSTONE_SLAB = 461
    SMOOTH_SANDSTONE_STAIRS = 462
    SANDSTONE_STAIRS = 463
    SMOOTH_STONE_SLAB = 464
    POLISHED_TUFF_SLAB = 465
    SMOOTH_QUARTZ_SLAB = 466
    GRANITE_STAIRS = 467
    OXIDIZED_CUT_COPPER_STAIRS = 468
    CUT_COPPER_SLAB = 469
    POLISHED_DEEPSLATE_WALL = 470
    DEEPSLATE_TILE_WALL = 471
    COBBLESTONE_WALL = 472
    SANDSTONE_WALL = 473
    DEEPSLATE_BRICK_WALL = 474
    BLACKSTONE_WALL = 475
    DIORITE_WALL = 476
    GRANITE_WALL = 477
    SPRUCE_FENCE = 480
    ACACIA_FENCE = 481
    OAK_FENCE = 482
    DARK_OAK_FENCE = 483
    JUNGLE_FENCE = 484
    OAK_FENCE_GATE = 485
    SPRUCE_TRAPDOOR = 490
    OAK_TRAPDOOR = 491
    OXIDIZED_COPPER_TRAPDOOR = 492
    COPPER_GRATE = 500
    OXIDIZED_COPPER_GRATE = 501
    COPPER_BULB = 502
    EXPOSED_COPPER_BULB = 503
    WEATHERED_COPPER_BULB = 504
    OXIDIZED_COPPER_BULB = 505
    CANDLE = 510
    WHITE_CANDLE = 511
    RED_CANDLE = 512
    WALL_TORCH = 513
    WHITE_BED = 520
    YELLOW_BED = 521
    GREEN_BED = 522
    RED_BED = 523
    LIME_BED = 524
    CYAN_BED = 525
    BLUE_BED = 526
    PURPLE_BED = 527
    ORANGE_BED = 528
    BROWN_BED = 529
    BROWN_WALL_BANNER = 530
    MAGENTA_WALL_BANNER = 531
    REDSTONE_WALL_TORCH = 532
    REDSTONE_DUST = 540
    REDSTONE_TORCH = 541
    LEVER = 542
    REPEATER = 543
    PISTON = 544
    STICKY_PISTON = 545
    PISTON_HEAD = 546


class Facing(Enum):
    NORTH = 0
    EAST = 1
    SOUTH = 2
    WEST = 3

    def opposite(self):
        return Facing((self.value + 2) % 4)

    def clockwise(self):
        return Facing((self.value + 1) % 4)

    def counterclockwise(self):
        return Facing((self.value - 1) % 4)

    @property
    def offset(self):
        return ((0, -1), (1, 0), (0, 1), (-1, 0))[self.value]


class SlabPosition(Enum):
    BOTTOM = 0
    TOP = 1


class StairShape(Enum):
    STRAIGHT = "straight"
    INNER_LEFT = "inner_left"
    INNER_RIGHT = "inner_right"
    OUTER_LEFT = "outer_left"
    OUTER_RIGHT = "outer_right"


class DoorHalf(Enum):
    LOWER = "lower"
    UPPER = "upper"


class DoorHinge(Enum):
    LEFT = "left"
    RIGHT = "right"


@dataclass
class BlockProperties:
    facing: Facing = Facing.SOUTH
    isOpen: bool = False
    slabPosition: SlabPosition = SlabPosition.BOTTOM
    stairShape: StairShape = StairShape.STRAIGHT
    doorHalf: DoorHalf = DoorHalf.LOWER
    doorHinge: DoorHinge = DoorHinge.LEFT
    oxidationStage: int = 0
    powered: bool = False
    redstonePower: int = 0
    repeaterDelay: int = 1
    repeaterLocked: bool = False
    pistonExtended: bool = False
    sticky: bool = False

    def copy(self):
        return BlockProperties(
            facing=self.facing,
            isOpen=self.isOpen,
            slabPosition=self.slabPosition,
            stairShape=self.stairShape,
            doorHalf=self.doorHalf,
            doorHinge=self.doorHinge,
            oxidationStage=self.oxidationStage,
            powered=self.powered,
            redstonePower=self.redstonePower,
            repeaterDelay=self.repeaterDelay,
            repeaterLocked=self.repeaterLocked,
            pistonExtended=self.pistonExtended,
            sticky=self.sticky,
        )
