"""Generated Java 1.16.1 registry and biome settings. See tools/export_biome_catalog.py."""
BIOMES = ({'category': 'OCEAN',
  'depth': -1.0,
  'dimension': 'overworld',
  'features': ['addOceanStructures',
               'addOceanCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addWaterBiomeOakTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addSeagrassOnStone',
               'addKelp',
               'addFrozenTopLayer'],
  'id': 'ocean',
  'raw_id': 0,
  'scale': 0.1,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/OceanBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.5},
 {'category': 'PLAINS',
  'depth': 0.125,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addPlainsTallGrass',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addPlainsFeatures',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'plains',
  'raw_id': 1,
  'scale': 0.05,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/PlainsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.8},
 {'category': 'DESERT',
  'depth': 0.125,
  'dimension': 'overworld',
  'features': ['addFossils',
               'addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDesertLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDesertDeadBushes',
               'addDefaultMushrooms',
               'addDesertVegetation',
               'addSprings',
               'addDesertFeatures',
               'addFrozenTopLayer'],
  'id': 'desert',
  'raw_id': 2,
  'scale': 0.05,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/DesertBiome.java',
  'surface': 'SAND_CONFIG',
  'temperature': 2.0},
 {'category': 'EXTREME_HILLS',
  'depth': 1.0,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addMountainTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addEmeraldOre',
               'addInfestedStone',
               'addFrozenTopLayer'],
  'id': 'mountains',
  'raw_id': 3,
  'scale': 0.5,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/MountainsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.2},
 {'category': 'FOREST',
  'depth': 0.1,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addForestFlowers',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addForestTrees',
               'addDefaultFlowers',
               'addForestGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'forest',
  'raw_id': 4,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/ForestBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.7},
 {'category': 'TAIGA',
  'depth': 0.2,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addLargeFerns',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addTaigaTrees',
               'addDefaultFlowers',
               'addTaigaGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addSweetBerryBushes',
               'addFrozenTopLayer'],
  'id': 'taiga',
  'raw_id': 5,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/TaigaBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.25},
 {'category': 'SWAMP',
  'depth': -0.2,
  'dimension': 'overworld',
  'features': ['addLandCarvers',
               'addFossils',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addClay',
               'addSwampFeatures',
               'addDefaultMushrooms',
               'addSwampVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'swamp',
  'raw_id': 6,
  'scale': 0.1,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/SwampBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.8},
 {'category': 'RIVER',
  'depth': -0.5,
  'dimension': 'overworld',
  'features': ['addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addWaterBiomeOakTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'river',
  'raw_id': 7,
  'scale': 0.0,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/RiverBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.5},
 {'category': 'NETHER',
  'depth': 0.1,
  'dimension': 'nether',
  'features': ['addDefaultMushrooms', 'addNetherMineables'],
  'id': 'nether_wastes',
  'raw_id': 8,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/NetherWastesBiome.java',
  'surface': 'NETHER_CONFIG',
  'temperature': 2.0},
 {'category': 'THEEND',
  'depth': 0.1,
  'dimension': 'end',
  'features': [],
  'id': 'the_end',
  'raw_id': 9,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/EndBiome.java',
  'surface': 'END_CONFIG',
  'temperature': 0.5},
 {'category': 'OCEAN',
  'depth': -1.0,
  'dimension': 'overworld',
  'features': ['addOceanStructures',
               'addOceanCarvers',
               'addDefaultLakes',
               'addIcebergs',
               'addDungeons',
               'addBlueIce',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addWaterBiomeOakTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'frozen_ocean',
  'raw_id': 10,
  'scale': 0.1,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/FrozenOceanBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.0},
 {'category': 'RIVER',
  'depth': -0.5,
  'dimension': 'overworld',
  'features': ['addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addWaterBiomeOakTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'frozen_river',
  'raw_id': 11,
  'scale': 0.0,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/FrozenRiverBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.0},
 {'category': 'ICY',
  'depth': 0.125,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addSnowySpruceTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'snowy_tundra',
  'raw_id': 12,
  'scale': 0.05,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/SnowyTundraBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.0},
 {'category': 'ICY',
  'depth': 0.45,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addSnowySpruceTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'snowy_mountains',
  'raw_id': 13,
  'scale': 0.3,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/SnowyMountainsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.0},
 {'category': 'MUSHROOM',
  'depth': 0.2,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addMushroomFieldsFeatures',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'mushroom_fields',
  'raw_id': 14,
  'scale': 0.3,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/MushroomFieldsBiome.java',
  'surface': 'MYCELIUM_CONFIG',
  'temperature': 0.9},
 {'category': 'MUSHROOM',
  'depth': 0.0,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addMushroomFieldsFeatures',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'mushroom_field_shore',
  'raw_id': 15,
  'scale': 0.025,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/MushroomFieldShoreBiome.java',
  'surface': 'MYCELIUM_CONFIG',
  'temperature': 0.9},
 {'category': 'BEACH',
  'depth': 0.0,
  'dimension': 'overworld',
  'features': ['addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'beach',
  'raw_id': 16,
  'scale': 0.025,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/BeachBiome.java',
  'surface': 'SAND_CONFIG',
  'temperature': 0.8},
 {'category': 'DESERT',
  'depth': 0.45,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDesertLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDesertDeadBushes',
               'addDefaultMushrooms',
               'addDesertVegetation',
               'addSprings',
               'addDesertFeatures',
               'addFrozenTopLayer'],
  'id': 'desert_hills',
  'raw_id': 17,
  'scale': 0.3,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/DesertHillsBiome.java',
  'surface': 'SAND_CONFIG',
  'temperature': 2.0},
 {'category': 'FOREST',
  'depth': 0.45,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addForestFlowers',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addForestTrees',
               'addDefaultFlowers',
               'addForestGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'wooded_hills',
  'raw_id': 18,
  'scale': 0.3,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/WoodedHillsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.7},
 {'category': 'TAIGA',
  'depth': 0.45,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addLargeFerns',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addTaigaTrees',
               'addDefaultFlowers',
               'addTaigaGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addSweetBerryBushes',
               'addFrozenTopLayer'],
  'id': 'taiga_hills',
  'raw_id': 19,
  'scale': 0.3,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/TaigaHillsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.25},
 {'category': 'EXTREME_HILLS',
  'depth': 0.8,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addExtraMountainTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addEmeraldOre',
               'addInfestedStone',
               'addFrozenTopLayer'],
  'id': 'mountain_edge',
  'raw_id': 20,
  'scale': 0.3,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/MountainEdgeBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.2},
 {'category': 'JUNGLE',
  'depth': 0.1,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addBamboo',
               'addJungleTrees',
               'addExtraDefaultFlowers',
               'addJungleGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addJungleVegetation',
               'addFrozenTopLayer'],
  'id': 'jungle',
  'raw_id': 21,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/JungleBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.95},
 {'category': 'JUNGLE',
  'depth': 0.45,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addBamboo',
               'addJungleTrees',
               'addExtraDefaultFlowers',
               'addJungleGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addJungleVegetation',
               'addFrozenTopLayer'],
  'id': 'jungle_hills',
  'raw_id': 22,
  'scale': 0.3,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/JungleHillsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.95},
 {'category': 'JUNGLE',
  'depth': 0.1,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addJungleEdgeTrees',
               'addExtraDefaultFlowers',
               'addJungleGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addJungleVegetation',
               'addFrozenTopLayer'],
  'id': 'jungle_edge',
  'raw_id': 23,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/JungleEdgeBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.95},
 {'category': 'OCEAN',
  'depth': -1.8,
  'dimension': 'overworld',
  'features': ['addOceanStructures',
               'addOceanCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addWaterBiomeOakTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addSeagrassOnStone',
               'addKelp',
               'addFrozenTopLayer'],
  'id': 'deep_ocean',
  'raw_id': 24,
  'scale': 0.1,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/DeepOceanBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.5},
 {'category': 'NONE',
  'depth': 0.1,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'stone_shore',
  'raw_id': 25,
  'scale': 0.8,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/StoneShoreBiome.java',
  'surface': 'STONE_CONFIG',
  'temperature': 0.2},
 {'category': 'BEACH',
  'depth': 0.0,
  'dimension': 'overworld',
  'features': ['addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'snowy_beach',
  'raw_id': 26,
  'scale': 0.025,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/SnowyBeachBiome.java',
  'surface': 'SAND_CONFIG',
  'temperature': 0.05},
 {'category': 'FOREST',
  'depth': 0.1,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addForestFlowers',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addBirchTrees',
               'addDefaultFlowers',
               'addForestGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'birch_forest',
  'raw_id': 27,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/BirchForestBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.6},
 {'category': 'FOREST',
  'depth': 0.45,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addForestFlowers',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addBirchTrees',
               'addDefaultFlowers',
               'addForestGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'birch_forest_hills',
  'raw_id': 28,
  'scale': 0.3,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/BirchForestHillsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.6},
 {'category': 'FOREST',
  'depth': 0.1,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addForestFlowers',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addDefaultFlowers',
               'addForestGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'dark_forest',
  'raw_id': 29,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/DarkForestBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.7},
 {'category': 'TAIGA',
  'depth': 0.2,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addLargeFerns',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addTaigaTrees',
               'addDefaultFlowers',
               'addTaigaGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addSweetBerryBushesSnowy',
               'addFrozenTopLayer'],
  'id': 'snowy_taiga',
  'raw_id': 30,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/SnowyTaigaBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': -0.5},
 {'category': 'TAIGA',
  'depth': 0.45,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addLargeFerns',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addTaigaTrees',
               'addDefaultFlowers',
               'addTaigaGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addSweetBerryBushesSnowy',
               'addFrozenTopLayer'],
  'id': 'snowy_taiga_hills',
  'raw_id': 31,
  'scale': 0.3,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/SnowyTaigaHillsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': -0.5},
 {'category': 'TAIGA',
  'depth': 0.2,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMossyRocks',
               'addLargeFerns',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addGiantTreeTaigaTrees',
               'addDefaultFlowers',
               'addGiantTaigaGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addSweetBerryBushes',
               'addFrozenTopLayer'],
  'id': 'giant_tree_taiga',
  'raw_id': 32,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/GiantTreeTaigaBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.3},
 {'category': 'TAIGA',
  'depth': 0.45,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMossyRocks',
               'addLargeFerns',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addGiantTreeTaigaTrees',
               'addDefaultFlowers',
               'addGiantTaigaGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addSweetBerryBushes',
               'addFrozenTopLayer'],
  'id': 'giant_tree_taiga_hills',
  'raw_id': 33,
  'scale': 0.3,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/GiantTreeTaigaHillsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.3},
 {'category': 'EXTREME_HILLS',
  'depth': 1.0,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addExtraMountainTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addEmeraldOre',
               'addInfestedStone',
               'addFrozenTopLayer'],
  'id': 'wooded_mountains',
  'raw_id': 34,
  'scale': 0.5,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/WoodedMountainsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.2},
 {'category': 'SAVANNA',
  'depth': 0.125,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addSavannaTallGrass',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addSavannaTrees',
               'addExtraDefaultFlowers',
               'addSavannaGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'savanna',
  'raw_id': 35,
  'scale': 0.05,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/SavannaBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 1.2},
 {'category': 'SAVANNA',
  'depth': 1.5,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addSavannaTallGrass',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addSavannaTrees',
               'addExtraDefaultFlowers',
               'addSavannaGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'savanna_plateau',
  'raw_id': 36,
  'scale': 0.025,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/SavannaPlateauBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 1.0},
 {'category': 'MESA',
  'depth': 0.1,
  'dimension': 'overworld',
  'features': ['addBadlandsUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addExtraGoldOre',
               'addDefaultDisks',
               'addBadlandsGrass',
               'addDefaultMushrooms',
               'addBadlandsVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'badlands',
  'raw_id': 37,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/BadlandsBiome.java',
  'surface': 'BADLANDS_CONFIG',
  'temperature': 2.0},
 {'category': 'MESA',
  'depth': 1.5,
  'dimension': 'overworld',
  'features': ['addBadlandsUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addExtraGoldOre',
               'addDefaultDisks',
               'addBadlandsPlateauTrees',
               'addBadlandsGrass',
               'addDefaultMushrooms',
               'addBadlandsVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'wooded_badlands_plateau',
  'raw_id': 38,
  'scale': 0.025,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/WoodedBadlandsPlateauBiome.java',
  'surface': 'BADLANDS_CONFIG',
  'temperature': 2.0},
 {'category': 'MESA',
  'depth': 1.5,
  'dimension': 'overworld',
  'features': ['addBadlandsUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addExtraGoldOre',
               'addDefaultDisks',
               'addBadlandsGrass',
               'addDefaultMushrooms',
               'addBadlandsVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'badlands_plateau',
  'raw_id': 39,
  'scale': 0.025,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/BadlandsPlateauBiome.java',
  'surface': 'BADLANDS_CONFIG',
  'temperature': 2.0},
 {'category': 'THEEND',
  'depth': 0.1,
  'dimension': 'end',
  'features': [],
  'id': 'small_end_islands',
  'raw_id': 40,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/EndIslandsSmallBiome.java',
  'surface': 'END_CONFIG',
  'temperature': 0.5},
 {'category': 'THEEND',
  'depth': 0.1,
  'dimension': 'end',
  'features': [],
  'id': 'end_midlands',
  'raw_id': 41,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/EndMidlandsBiome.java',
  'surface': 'END_CONFIG',
  'temperature': 0.5},
 {'category': 'THEEND',
  'depth': 0.1,
  'dimension': 'end',
  'features': [],
  'id': 'end_highlands',
  'raw_id': 42,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/EndHighlandsBiome.java',
  'surface': 'END_CONFIG',
  'temperature': 0.5},
 {'category': 'THEEND',
  'depth': 0.1,
  'dimension': 'end',
  'features': [],
  'id': 'end_barrens',
  'raw_id': 43,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/EndBarrensBiome.java',
  'surface': 'END_CONFIG',
  'temperature': 0.5},
 {'category': 'OCEAN',
  'depth': -1.0,
  'dimension': 'overworld',
  'features': ['addOceanStructures',
               'addOceanCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addWaterBiomeOakTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addSeagrass',
               'addFrozenTopLayer'],
  'id': 'warm_ocean',
  'raw_id': 44,
  'scale': 0.1,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/WarmOceanBiome.java',
  'surface': 'SAND_SAND_UNDERWATER_CONFIG',
  'temperature': 0.5},
 {'category': 'OCEAN',
  'depth': -1.0,
  'dimension': 'overworld',
  'features': ['addOceanStructures',
               'addOceanCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addWaterBiomeOakTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addSeagrass',
               'addLessKelp',
               'addFrozenTopLayer'],
  'id': 'lukewarm_ocean',
  'raw_id': 45,
  'scale': 0.1,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/LukewarmOceanBiome.java',
  'surface': 'GRASS_SAND_UNDERWATER_CONFIG',
  'temperature': 0.5},
 {'category': 'OCEAN',
  'depth': -1.0,
  'dimension': 'overworld',
  'features': ['addOceanStructures',
               'addOceanCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addWaterBiomeOakTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addSeagrassOnStone',
               'addKelp',
               'addFrozenTopLayer'],
  'id': 'cold_ocean',
  'raw_id': 46,
  'scale': 0.1,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/ColdOceanBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.5},
 {'category': 'OCEAN',
  'depth': -1.8,
  'dimension': 'overworld',
  'features': ['addOceanStructures',
               'addOceanCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addWaterBiomeOakTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addMoreSeagrass',
               'addSeagrassOnStone',
               'addFrozenTopLayer'],
  'id': 'deep_warm_ocean',
  'raw_id': 47,
  'scale': 0.1,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/DeepWarmOceanBiome.java',
  'surface': 'SAND_SAND_UNDERWATER_CONFIG',
  'temperature': 0.5},
 {'category': 'OCEAN',
  'depth': -1.8,
  'dimension': 'overworld',
  'features': ['addOceanStructures',
               'addOceanCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addWaterBiomeOakTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addMoreSeagrass',
               'addSeagrassOnStone',
               'addLessKelp',
               'addFrozenTopLayer'],
  'id': 'deep_lukewarm_ocean',
  'raw_id': 48,
  'scale': 0.1,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/DeepLukewarmOceanBiome.java',
  'surface': 'GRASS_SAND_UNDERWATER_CONFIG',
  'temperature': 0.5},
 {'category': 'OCEAN',
  'depth': -1.8,
  'dimension': 'overworld',
  'features': ['addOceanStructures',
               'addOceanCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addWaterBiomeOakTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addSeagrassOnStone',
               'addKelp',
               'addFrozenTopLayer'],
  'id': 'deep_cold_ocean',
  'raw_id': 49,
  'scale': 0.1,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/DeepColdOceanBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.5},
 {'category': 'OCEAN',
  'depth': -1.8,
  'dimension': 'overworld',
  'features': ['addOceanStructures',
               'addOceanCarvers',
               'addDefaultLakes',
               'addIcebergs',
               'addDungeons',
               'addBlueIce',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addWaterBiomeOakTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'deep_frozen_ocean',
  'raw_id': 50,
  'scale': 0.1,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/DeepFrozenOceanBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.5},
 {'category': 'NONE',
  'depth': 0.1,
  'dimension': 'overworld',
  'features': [],
  'id': 'the_void',
  'raw_id': 127,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/VoidBiome.java',
  'surface': 'STONE_CONFIG',
  'temperature': 0.5},
 {'category': 'PLAINS',
  'depth': 0.125,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addPlainsTallGrass',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addPlainsFeatures',
               'addDefaultMushrooms',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'sunflower_plains',
  'raw_id': 129,
  'scale': 0.05,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/SunflowerPlainsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.8},
 {'category': 'DESERT',
  'depth': 0.225,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDesertLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDesertDeadBushes',
               'addDefaultMushrooms',
               'addDesertVegetation',
               'addSprings',
               'addDesertFeatures',
               'addFrozenTopLayer'],
  'id': 'desert_lakes',
  'raw_id': 130,
  'scale': 0.25,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/DesertLakesBiome.java',
  'surface': 'SAND_CONFIG',
  'temperature': 2.0},
 {'category': 'EXTREME_HILLS',
  'depth': 1.0,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addMountainTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addEmeraldOre',
               'addInfestedStone',
               'addFrozenTopLayer'],
  'id': 'gravelly_mountains',
  'raw_id': 131,
  'scale': 0.5,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/GravellyMountainsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.2},
 {'category': 'FOREST',
  'depth': 0.1,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'flower_forest',
  'raw_id': 132,
  'scale': 0.4,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/FlowerForestBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.7},
 {'category': 'TAIGA',
  'depth': 0.3,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addLargeFerns',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addTaigaTrees',
               'addDefaultFlowers',
               'addTaigaGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addSweetBerryBushes',
               'addFrozenTopLayer'],
  'id': 'taiga_mountains',
  'raw_id': 133,
  'scale': 0.4,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/TaigaMountainsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.25},
 {'category': 'SWAMP',
  'depth': -0.1,
  'dimension': 'overworld',
  'features': ['addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addClay',
               'addSwampFeatures',
               'addDefaultMushrooms',
               'addSwampVegetation',
               'addSprings',
               'addFossils',
               'addFrozenTopLayer'],
  'id': 'swamp_hills',
  'raw_id': 134,
  'scale': 0.3,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/SwampHillsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.8},
 {'category': 'ICY',
  'depth': 0.425,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addSnowySpruceTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'ice_spikes',
  'raw_id': 140,
  'scale': 0.45000002,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/IceSpikesBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.0},
 {'category': 'JUNGLE',
  'depth': 0.2,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addJungleTrees',
               'addExtraDefaultFlowers',
               'addJungleGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addJungleVegetation',
               'addFrozenTopLayer'],
  'id': 'modified_jungle',
  'raw_id': 149,
  'scale': 0.4,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/ModifiedJungleBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.95},
 {'category': 'JUNGLE',
  'depth': 0.2,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addJungleEdgeTrees',
               'addExtraDefaultFlowers',
               'addJungleGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addJungleVegetation',
               'addFrozenTopLayer'],
  'id': 'modified_jungle_edge',
  'raw_id': 151,
  'scale': 0.4,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/ModifiedJungleEdgeBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.95},
 {'category': 'FOREST',
  'depth': 0.2,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addForestFlowers',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addTallBirchTrees',
               'addDefaultFlowers',
               'addForestGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'tall_birch_forest',
  'raw_id': 155,
  'scale': 0.4,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/TallBirchForestBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.6},
 {'category': 'FOREST',
  'depth': 0.55,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addForestFlowers',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addTallBirchTrees',
               'addDefaultFlowers',
               'addForestGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'tall_birch_hills',
  'raw_id': 156,
  'scale': 0.5,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/TallBirchHillsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.6},
 {'category': 'FOREST',
  'depth': 0.2,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addForestFlowers',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addDefaultFlowers',
               'addForestGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'dark_forest_hills',
  'raw_id': 157,
  'scale': 0.4,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/DarkForestHillsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.7},
 {'category': 'TAIGA',
  'depth': 0.3,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addLargeFerns',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addTaigaTrees',
               'addDefaultFlowers',
               'addTaigaGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addSweetBerryBushesSnowy',
               'addFrozenTopLayer'],
  'id': 'snowy_taiga_mountains',
  'raw_id': 158,
  'scale': 0.4,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/SnowyTaigaMountainsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': -0.5},
 {'category': 'TAIGA',
  'depth': 0.2,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMossyRocks',
               'addLargeFerns',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addGiantSpruceTaigaTrees',
               'addDefaultFlowers',
               'addGiantTaigaGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addSweetBerryBushes',
               'addFrozenTopLayer'],
  'id': 'giant_spruce_taiga',
  'raw_id': 160,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/GiantSpruceTaigaBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.25},
 {'category': 'TAIGA',
  'depth': 0.2,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMossyRocks',
               'addLargeFerns',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addGiantSpruceTaigaTrees',
               'addDefaultFlowers',
               'addGiantTaigaGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addSweetBerryBushes',
               'addFrozenTopLayer'],
  'id': 'giant_spruce_taiga_hills',
  'raw_id': 161,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/GiantSpruceTaigaHillsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.25},
 {'category': 'EXTREME_HILLS',
  'depth': 1.0,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addMountainTrees',
               'addDefaultFlowers',
               'addDefaultGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addEmeraldOre',
               'addInfestedStone',
               'addFrozenTopLayer'],
  'id': 'modified_gravelly_mountains',
  'raw_id': 162,
  'scale': 0.5,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/ModifiedGravellyMountainsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.2},
 {'category': 'SAVANNA',
  'depth': 0.3625,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addExtraSavannaTrees',
               'addDefaultFlowers',
               'addShatteredSavannaGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'shattered_savanna',
  'raw_id': 163,
  'scale': 1.225,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/ShatteredSavannaBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 1.1},
 {'category': 'SAVANNA',
  'depth': 1.05,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addExtraSavannaTrees',
               'addDefaultFlowers',
               'addShatteredSavannaGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'shattered_savanna_plateau',
  'raw_id': 164,
  'scale': 1.2125001,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/ShatteredSavannaPlateauBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 1.0},
 {'category': 'MESA',
  'depth': 0.1,
  'dimension': 'overworld',
  'features': ['addBadlandsUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addExtraGoldOre',
               'addDefaultDisks',
               'addBadlandsGrass',
               'addDefaultMushrooms',
               'addBadlandsVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'eroded_badlands',
  'raw_id': 165,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/ErodedBadlandsBiome.java',
  'surface': 'BADLANDS_CONFIG',
  'temperature': 2.0},
 {'category': 'MESA',
  'depth': 0.45,
  'dimension': 'overworld',
  'features': ['addBadlandsUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addExtraGoldOre',
               'addDefaultDisks',
               'addBadlandsPlateauTrees',
               'addBadlandsGrass',
               'addDefaultMushrooms',
               'addBadlandsVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'modified_wooded_badlands_plateau',
  'raw_id': 166,
  'scale': 0.3,
  'source': 'Game '
            'Reference/05_mapped_sources/net/minecraft/world/biome/ModifiedWoodedBadlandsPlateauBiome.java',
  'surface': 'BADLANDS_CONFIG',
  'temperature': 2.0},
 {'category': 'MESA',
  'depth': 0.45,
  'dimension': 'overworld',
  'features': ['addBadlandsUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addExtraGoldOre',
               'addDefaultDisks',
               'addBadlandsGrass',
               'addDefaultMushrooms',
               'addBadlandsVegetation',
               'addSprings',
               'addFrozenTopLayer'],
  'id': 'modified_badlands_plateau',
  'raw_id': 167,
  'scale': 0.3,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/ModifiedBadlandsPlateauBiome.java',
  'surface': 'BADLANDS_CONFIG',
  'temperature': 2.0},
 {'category': 'JUNGLE',
  'depth': 0.1,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addBambooJungleTrees',
               'addExtraDefaultFlowers',
               'addJungleGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addJungleVegetation',
               'addFrozenTopLayer'],
  'id': 'bamboo_jungle',
  'raw_id': 168,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/BambooJungleBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.95},
 {'category': 'JUNGLE',
  'depth': 0.45,
  'dimension': 'overworld',
  'features': ['addDefaultUndergroundStructures',
               'addLandCarvers',
               'addDefaultLakes',
               'addDungeons',
               'addMineables',
               'addDefaultOres',
               'addDefaultDisks',
               'addBambooJungleTrees',
               'addExtraDefaultFlowers',
               'addJungleGrass',
               'addDefaultMushrooms',
               'addDefaultVegetation',
               'addSprings',
               'addJungleVegetation',
               'addFrozenTopLayer'],
  'id': 'bamboo_jungle_hills',
  'raw_id': 169,
  'scale': 0.3,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/BambooJungleHillsBiome.java',
  'surface': 'GRASS_CONFIG',
  'temperature': 0.95},
 {'category': 'NETHER',
  'depth': 0.1,
  'dimension': 'nether',
  'features': ['addNetherMineables'],
  'id': 'soul_sand_valley',
  'raw_id': 170,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/SoulSandValleyBiome.java',
  'surface': 'SOUL_SAND_CONFIG',
  'temperature': 2.0},
 {'category': 'NETHER',
  'depth': 0.1,
  'dimension': 'nether',
  'features': ['addDefaultMushrooms', 'addCrimsonForestVegetation', 'addNetherMineables'],
  'id': 'crimson_forest',
  'raw_id': 171,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/CrimsonForestBiome.java',
  'surface': 'CRIMSON_NYLIUM_CONFIG',
  'temperature': 2.0},
 {'category': 'NETHER',
  'depth': 0.1,
  'dimension': 'nether',
  'features': ['addDefaultMushrooms', 'addWarpedForestVegetation', 'addNetherMineables'],
  'id': 'warped_forest',
  'raw_id': 172,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/WarpedForestBiome.java',
  'surface': 'WARPED_NYLIUM_CONFIG',
  'temperature': 2.0},
 {'category': 'NETHER',
  'depth': 0.1,
  'dimension': 'nether',
  'features': ['addAncientDebris'],
  'id': 'basalt_deltas',
  'raw_id': 173,
  'scale': 0.2,
  'source': 'Game Reference/05_mapped_sources/net/minecraft/world/biome/BasaltDeltasBiome.java',
  'surface': 'BASALT_DELTA_CONFIG',
  'temperature': 2.0})
BY_ID = {entry["id"]: entry for entry in BIOMES}
