"""Java 1.16.1 piston, comparator and wall-torch element geometry and UVs.

Copied from Game Reference/02_jar_extracted/client/assets/minecraft/models/block.
Keys body, extended, head and wall_torch refer to template_piston,
piston_extended, template_piston_head and template_torch_wall respectively.
Comparator keys match the source filenames. Coordinates use Java x/y/z.
"""

PISTON_ELEMENTS = {'body': [{'from': [0, 0, 0],
           'to': [16, 16, 16],
           'faces': {'down': {'uv': [0, 0, 16, 16],
                              'texture': '#side',
                              'rotation': 180,
                              'cullface': 'down'},
                     'up': {'uv': [0, 0, 16, 16], 'texture': '#side', 'cullface': 'up'},
                     'north': {'uv': [0, 0, 16, 16], 'texture': '#platform', 'cullface': 'north'},
                     'south': {'uv': [0, 0, 16, 16], 'texture': '#bottom', 'cullface': 'south'},
                     'west': {'uv': [0, 0, 16, 16],
                              'texture': '#side',
                              'rotation': 270,
                              'cullface': 'west'},
                     'east': {'uv': [0, 0, 16, 16],
                              'texture': '#side',
                              'rotation': 90,
                              'cullface': 'east'}}}],
 'extended': [{'from': [0, 0, 4],
               'to': [16, 16, 16],
               'faces': {'down': {'uv': [0, 4, 16, 16],
                                  'texture': '#side',
                                  'cullface': 'down',
                                  'rotation': 180},
                         'up': {'uv': [0, 4, 16, 16], 'texture': '#side', 'cullface': 'up'},
                         'north': {'uv': [0, 0, 16, 16], 'texture': '#inside'},
                         'south': {'uv': [0, 0, 16, 16], 'texture': '#bottom', 'cullface': 'south'},
                         'west': {'uv': [0, 4, 16, 16],
                                  'texture': '#side',
                                  'cullface': 'west',
                                  'rotation': 270},
                         'east': {'uv': [0, 4, 16, 16],
                                  'texture': '#side',
                                  'cullface': 'east',
                                  'rotation': 90}}}],
 'head': [{'from': [0, 0, 0],
           'to': [16, 16, 4],
           'faces': {'down': {'uv': [0, 0, 16, 4],
                              'texture': '#side',
                              'cullface': 'down',
                              'rotation': 180},
                     'up': {'uv': [0, 0, 16, 4], 'texture': '#side', 'cullface': 'up'},
                     'north': {'uv': [0, 0, 16, 16], 'texture': '#platform', 'cullface': 'north'},
                     'south': {'uv': [0, 0, 16, 16], 'texture': '#unsticky'},
                     'west': {'uv': [0, 0, 16, 4],
                              'texture': '#side',
                              'rotation': 270,
                              'cullface': 'west'},
                     'east': {'uv': [0, 0, 16, 4],
                              'texture': '#side',
                              'rotation': 90,
                              'cullface': 'east'}}},
          {'from': [6, 6, 4],
           'to': [10, 10, 20],
           'faces': {'down': {'uv': [0, 0, 16, 4], 'texture': '#side', 'rotation': 90},
                     'up': {'uv': [0, 0, 16, 4], 'texture': '#side', 'rotation': 270},
                     'west': {'uv': [16, 4, 0, 0], 'texture': '#side'},
                     'east': {'uv': [0, 0, 16, 4], 'texture': '#side'}}}],
 'wall_torch': [{'from': [-1, 3.5, 7],
                 'to': [1, 13.5, 9],
                 'rotation': {'origin': [0, 3.5, 8], 'axis': 'z', 'angle': -22.5},
                 'shade': False,
                 'faces': {'down': {'uv': [7, 13, 9, 15], 'texture': '#torch'},
                           'up': {'uv': [7, 6, 9, 8], 'texture': '#torch'}}},
                {'from': [-1, 3.5, 0],
                 'to': [1, 19.5, 16],
                 'rotation': {'origin': [0, 3.5, 8], 'axis': 'z', 'angle': -22.5},
                 'shade': False,
                 'faces': {'west': {'uv': [0, 0, 16, 16], 'texture': '#torch'},
                           'east': {'uv': [0, 0, 16, 16], 'texture': '#torch'}}},
                {'from': [-8, 3.5, 7],
                 'to': [8, 19.5, 9],
                 'rotation': {'origin': [0, 3.5, 8], 'axis': 'z', 'angle': -22.5},
                 'shade': False,
                 'faces': {'north': {'uv': [0, 0, 16, 16], 'texture': '#torch'},
                           'south': {'uv': [0, 0, 16, 16], 'texture': '#torch'}}}],
 'comparator': [{'from': [0, 0, 0],
                 'to': [16, 2, 16],
                 'faces': {'down': {'uv': [0, 0, 16, 16], 'texture': '#slab', 'cullface': 'down'},
                           'up': {'uv': [0, 0, 16, 16], 'texture': '#top'},
                           'north': {'uv': [0, 14, 16, 16],
                                     'texture': '#slab',
                                     'cullface': 'north'},
                           'south': {'uv': [0, 14, 16, 16],
                                     'texture': '#slab',
                                     'cullface': 'south'},
                           'west': {'uv': [0, 14, 16, 16], 'texture': '#slab', 'cullface': 'west'},
                           'east': {'uv': [0, 14, 16, 16],
                                    'texture': '#slab',
                                    'cullface': 'east'}}},
                {'from': [4, 2, 11],
                 'to': [6, 7, 13],
                 'faces': {'down': {'uv': [7, 13, 9, 15], 'texture': '#unlit'},
                           'up': {'uv': [7, 6, 9, 8], 'texture': '#unlit'},
                           'north': {'uv': [7, 6, 9, 11], 'texture': '#unlit'},
                           'south': {'uv': [7, 6, 9, 11], 'texture': '#unlit'},
                           'west': {'uv': [7, 6, 9, 11], 'texture': '#unlit'},
                           'east': {'uv': [7, 6, 9, 11], 'texture': '#unlit'}}},
                {'from': [10, 2, 11],
                 'to': [12, 7, 13],
                 'faces': {'down': {'uv': [7, 13, 9, 15], 'texture': '#unlit'},
                           'up': {'uv': [7, 6, 9, 8], 'texture': '#unlit'},
                           'north': {'uv': [7, 6, 9, 11], 'texture': '#unlit'},
                           'south': {'uv': [7, 6, 9, 11], 'texture': '#unlit'},
                           'west': {'uv': [7, 6, 9, 11], 'texture': '#unlit'},
                           'east': {'uv': [7, 6, 9, 11], 'texture': '#unlit'}}},
                {'from': [7, 2, 2],
                 'to': [9, 4, 4],
                 'faces': {'down': {'uv': [7, 13, 9, 15], 'texture': '#unlit'},
                           'up': {'uv': [7, 6, 9, 8], 'texture': '#unlit'},
                           'north': {'uv': [7, 6, 9, 8], 'texture': '#unlit'},
                           'south': {'uv': [7, 6, 9, 8], 'texture': '#unlit'},
                           'west': {'uv': [7, 6, 9, 8], 'texture': '#unlit'},
                           'east': {'uv': [7, 6, 9, 8], 'texture': '#unlit'}}}],
 'comparator_on': [{'from': [0, 0, 0],
                    'to': [16, 2, 16],
                    'faces': {'down': {'uv': [0, 0, 16, 16],
                                       'texture': '#slab',
                                       'cullface': 'down'},
                              'up': {'uv': [0, 0, 16, 16], 'texture': '#top'},
                              'north': {'uv': [0, 14, 16, 16],
                                        'texture': '#slab',
                                        'cullface': 'north'},
                              'south': {'uv': [0, 14, 16, 16],
                                        'texture': '#slab',
                                        'cullface': 'south'},
                              'west': {'uv': [0, 14, 16, 16],
                                       'texture': '#slab',
                                       'cullface': 'west'},
                              'east': {'uv': [0, 14, 16, 16],
                                       'texture': '#slab',
                                       'cullface': 'east'}}},
                   {'from': [4, 7, 11],
                    'to': [6, 7, 13],
                    'faces': {'up': {'uv': [7, 6, 9, 8], 'texture': '#lit'}}},
                   {'from': [4, 2, 10],
                    'to': [6, 8, 14],
                    'faces': {'west': {'uv': [6, 5, 10, 11], 'texture': '#lit'},
                              'east': {'uv': [6, 5, 10, 11], 'texture': '#lit'}}},
                   {'from': [3, 2, 11],
                    'to': [7, 8, 13],
                    'faces': {'north': {'uv': [6, 5, 10, 11], 'texture': '#lit'},
                              'south': {'uv': [6, 5, 10, 11], 'texture': '#lit'}}},
                   {'from': [10, 7, 11],
                    'to': [12, 7, 13],
                    'faces': {'up': {'uv': [7, 6, 9, 8], 'texture': '#lit'}}},
                   {'from': [10, 2, 10],
                    'to': [12, 8, 14],
                    'faces': {'west': {'uv': [6, 5, 10, 11], 'texture': '#lit'},
                              'east': {'uv': [6, 5, 10, 11], 'texture': '#lit'}}},
                   {'from': [9, 2, 11],
                    'to': [13, 8, 13],
                    'faces': {'north': {'uv': [6, 5, 10, 11], 'texture': '#lit'},
                              'south': {'uv': [6, 5, 10, 11], 'texture': '#lit'}}},
                   {'from': [7, 2, 2],
                    'to': [9, 4, 4],
                    'faces': {'down': {'uv': [7, 13, 9, 15], 'texture': '#unlit'},
                              'up': {'uv': [7, 6, 9, 8], 'texture': '#unlit'},
                              'north': {'uv': [7, 6, 9, 8], 'texture': '#unlit'},
                              'south': {'uv': [7, 6, 9, 8], 'texture': '#unlit'},
                              'west': {'uv': [7, 6, 9, 8], 'texture': '#unlit'},
                              'east': {'uv': [7, 6, 9, 8], 'texture': '#unlit'}}}],
 'comparator_subtract': [{'from': [0, 0, 0],
                          'to': [16, 2, 16],
                          'faces': {'down': {'uv': [0, 0, 16, 16],
                                             'texture': '#slab',
                                             'cullface': 'down'},
                                    'up': {'uv': [0, 0, 16, 16], 'texture': '#top'},
                                    'north': {'uv': [0, 14, 16, 16],
                                              'texture': '#slab',
                                              'cullface': 'north'},
                                    'south': {'uv': [0, 14, 16, 16],
                                              'texture': '#slab',
                                              'cullface': 'south'},
                                    'west': {'uv': [0, 14, 16, 16],
                                             'texture': '#slab',
                                             'cullface': 'west'},
                                    'east': {'uv': [0, 14, 16, 16],
                                             'texture': '#slab',
                                             'cullface': 'east'}}},
                         {'from': [4, 2, 11],
                          'to': [6, 7, 13],
                          'faces': {'down': {'uv': [7, 13, 9, 15], 'texture': '#unlit'},
                                    'up': {'uv': [7, 6, 9, 8], 'texture': '#unlit'},
                                    'north': {'uv': [7, 6, 9, 11], 'texture': '#unlit'},
                                    'south': {'uv': [7, 6, 9, 11], 'texture': '#unlit'},
                                    'west': {'uv': [7, 6, 9, 11], 'texture': '#unlit'},
                                    'east': {'uv': [7, 6, 9, 11], 'texture': '#unlit'}}},
                         {'from': [10, 2, 11],
                          'to': [12, 7, 13],
                          'faces': {'down': {'uv': [7, 13, 9, 15], 'texture': '#unlit'},
                                    'up': {'uv': [7, 6, 9, 8], 'texture': '#unlit'},
                                    'north': {'uv': [7, 6, 9, 11], 'texture': '#unlit'},
                                    'south': {'uv': [7, 6, 9, 11], 'texture': '#unlit'},
                                    'west': {'uv': [7, 6, 9, 11], 'texture': '#unlit'},
                                    'east': {'uv': [7, 6, 9, 11], 'texture': '#unlit'}}},
                         {'from': [7, 5, 2],
                          'to': [9, 5, 4],
                          'faces': {'up': {'uv': [7, 6, 9, 8], 'texture': '#lit'}}},
                         {'from': [7, 2, 1],
                          'to': [9, 6, 5],
                          'faces': {'west': {'uv': [6, 5, 10, 9], 'texture': '#lit'},
                                    'east': {'uv': [6, 5, 10, 9], 'texture': '#lit'}}},
                         {'from': [6, 2, 2],
                          'to': [10, 6, 4],
                          'faces': {'north': {'uv': [6, 5, 10, 9], 'texture': '#lit'},
                                    'south': {'uv': [6, 5, 10, 9], 'texture': '#lit'}}}],
 'comparator_on_subtract': [{'from': [0, 0, 0],
                             'to': [16, 2, 16],
                             'faces': {'down': {'uv': [0, 0, 16, 16],
                                                'texture': '#slab',
                                                'cullface': 'down'},
                                       'up': {'uv': [0, 0, 16, 16], 'texture': '#top'},
                                       'north': {'uv': [0, 14, 16, 16],
                                                 'texture': '#slab',
                                                 'cullface': 'north'},
                                       'south': {'uv': [0, 14, 16, 16],
                                                 'texture': '#slab',
                                                 'cullface': 'south'},
                                       'west': {'uv': [0, 14, 16, 16],
                                                'texture': '#slab',
                                                'cullface': 'west'},
                                       'east': {'uv': [0, 14, 16, 16],
                                                'texture': '#slab',
                                                'cullface': 'east'}}},
                            {'from': [4, 7, 11],
                             'to': [6, 7, 13],
                             'faces': {'up': {'uv': [7, 6, 9, 8], 'texture': '#lit'}}},
                            {'from': [4, 2, 10],
                             'to': [6, 8, 14],
                             'faces': {'west': {'uv': [6, 5, 10, 11], 'texture': '#lit'},
                                       'east': {'uv': [6, 5, 10, 11], 'texture': '#lit'}}},
                            {'from': [3, 2, 11],
                             'to': [7, 8, 13],
                             'faces': {'north': {'uv': [6, 5, 10, 11], 'texture': '#lit'},
                                       'south': {'uv': [6, 5, 10, 11], 'texture': '#lit'}}},
                            {'from': [10, 7, 11],
                             'to': [12, 7, 13],
                             'faces': {'up': {'uv': [7, 6, 9, 8], 'texture': '#lit'}}},
                            {'from': [10, 2, 10],
                             'to': [12, 8, 14],
                             'faces': {'west': {'uv': [6, 5, 10, 11], 'texture': '#lit'},
                                       'east': {'uv': [6, 5, 10, 11], 'texture': '#lit'}}},
                            {'from': [9, 2, 11],
                             'to': [13, 8, 13],
                             'faces': {'north': {'uv': [6, 5, 10, 11], 'texture': '#lit'},
                                       'south': {'uv': [6, 5, 10, 11], 'texture': '#lit'}}},
                            {'from': [7, 5, 2],
                             'to': [9, 5, 4],
                             'faces': {'up': {'uv': [7, 6, 9, 8], 'texture': '#lit'}}},
                            {'from': [7, 2, 1],
                             'to': [9, 6, 5],
                             'faces': {'west': {'uv': [6, 5, 10, 9], 'texture': '#lit'},
                                       'east': {'uv': [6, 5, 10, 9], 'texture': '#lit'}}},
                            {'from': [6, 2, 2],
                             'to': [10, 6, 4],
                             'faces': {'north': {'uv': [6, 5, 10, 9], 'texture': '#lit'},
                                       'south': {'uv': [6, 5, 10, 9], 'texture': '#lit'}}}]}
